### ISSUE TITLE
Some op feats suggestion

### ISSUE THREAD

**Issue by ssebaa** [JohN100x1/WOTR_IsekaiMod#91] opened 2023-03-16 22:54 UTC
How about making a feat that allows you to use spell as swift action (sorcerers reflex i think) available for whole fight not for first round only and making it an overpowered ability and/or add additional feat that allows you to cast spell or ability as movement action so u can get max two or three spells per round?

**Comment by JohN100x1** [comment] 2023-03-16 23:15
Duplicate of #2

**Closed** 2023-03-16 23:16 UTC
Labels: enhancement
