### ISSUE TITLE
Legacy Prestige Class

### ISSUE THREAD

**Issue by Mavroz** [JohN100x1/WOTR_IsekaiMod#137] opened 2023-04-18 03:26 UTC
First of all, I love your mod.
Second, I was thinking since you added the legacy class, it would be a lot but you could put that at level 10 you can choose a legacy of the prestige classes. Maybe having to meet the requirements.It's just an idea.
Thank you very much for the mod.

**Comment by JohN100x1** [comment] 2023-04-18 10:28
duplicate of #126

**Closed by JohN100x1** 2023-04-18 10:28 UTC
Labels: enhancement
